name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: kivy/buildozer-action@v1
        with:
          buildozer_command: buildozer android debug
